variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: COMP367 Lab 4
  pool:
    name: offlineagent
  steps:
  - checkout: self
    fetchDepth: 1
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
  - task: DotNetCoreCLI@2
    displayName: Nuget Push
    inputs:
      command: push
      feedPublish: 0b05eb25-4f6a-4a14-9256-6ce749fb7669/2265d3b4-4fc3-4e3b-ad8c-f87d34587f2a
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
